version: '3.8'

services:
  backend:
    build:
      context: ./PruebaGrupoLagosBackend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - app-network

  frontend:
    build:
      context: ./PruebaGrupoLagosFrontend
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    environment:
      - API_URL=http://backend:8080 
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
